#project.version.toml

[versions]
compileSdk = "33"
minSdk = "21"
targetSdk = "32"
versionCode = "1"
versionName = "1.0.0"

coreKtx = "1.8.0"
appcompat = "1.3.0"
material = "1.6.1"
constraintlayout = "2.1.4"
coordinatorlayout = "1.2.0"

lifecycleKtx = "2.5.0"
appcompat = "1.6.0-alpha05"
coroutines = "1.6.4"

logging = "3.6.0"
okhttp3="3.12.0"
retrofit2="2.6.0"


[libraries]
coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
coordinatorlayout = { module = "androidx.coordinatorlayout:coordinatorlayout", version.ref = "coordinatorlayout" }

lifecycleKtx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleKtx" }
lifecycleKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleKtx" }

appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }

coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "logging" }
okhttp3={ module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp3" }
retrofit2={ module = "com.squareup.retrofit2:adapter-rxjava2", version.ref = "retrofit2" }
retrofit2={ module = "com.squareup.retrofit2:adapter-rxjava", version.ref = "retrofit2" }
retrofit2={ module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit2" }
retrofit2={ module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit2" }
retrofit2={ module = "com.squareup.retrofit2:adapter-rxjava2", version.ref = "retrofit2" }

[bundles]
andorid_base = ["coreKtx", "appcompat", "material", "constraintlayout"]

[plugins]
application = { id = "com.android.application" }
